### PR TITLE
added David Mentré's FIXME macro to templates to facilitate adding comments

### PR DESCRIPTION
**Pull request by mgudemann**
added David Mentre's FIXME macro to the template class files
this allows to add easily visible comments to a latex file

### CODE REVIEW

**Comment by JonasHelming** [comment]
Thanks for the contribution. Could you also provide a wiki page describing how to use this?
That would be great...

**Comment by JonasHelming** [comment]
additionally, I need you to follow this: https://github.com/openETCS/ecosystem/wiki/Contribution-Guidelines
to accept your contribution

**Comment by mgudemann** [comment]
Name: Macro to allow comments in openETCS Latex template
Description: This macro allows to add a comment to a Latex file which will appear in the resulting pdf document. A comment is added using \FIXME{comment} and will be clearly visibly rendered in the resulting document. It was created by David Mentre for use in the ETCS-benchmark.tex file.
Author(s): David Mentre
I hereby declare that I accept to contribute following the openETCS terms of use and the openETCS IP policy.

http://openetcs.org/termsofuse/

https://github.com/openETCS/ecosystem/wiki/IP-Policy

**Comment by mgudemann** [comment]
Hi Jonas,

I added the comment to the issue.
Sorry for the inconvenience, I hope it is now ok.

Regards
Matthias

**Pull request merged**
